### ISSUE TITLE
new update broke hiscores again

### ISSUE THREAD

**Issue by tylersfd2** [phongse/pyosrs#20]
new update

**Comment by tylersfd2** [comment]
I found a different endpoint that returns JSON. I don't know if that was available when you created this. It might fix the positional issues created when new items are added to the hiscores. This might be of use.

https://secure.runescape.com/m=hiscore_oldschool/index_lite.json?player=zezima

**Comment by phongse** [comment]
> I found a different endpoint that returns JSON. I don't know if that was available when you created this. It might fix the positional issues created when new items are added to the hiscores. This might be of use.
> 
> https://secure.runescape.com/m=hiscore_oldschool/index_lite.json?player=zezima

About time that they created an endpoint which returned JSON. Thanks for the heads up!

I'll probably fix the update from the old endpoint first. Looks like it's the new Deadman mode and perhaps League mode. Will have to take a closer look later today.

The new JSON endpoint would probably be in 0.1.0 at some point in the future :)

**Comment by tylersfd2** [comment]
Sidenote: I use your lib to check player stats / kcs /inferno cape, etc., when applying to our clan.  So when the game updates I'm always a little nervous they randomly change the hiscores 😆

**Comment by phongse** [comment]
Fixed in 0.0.7 😄
